### ISSUE TITLE
Invitation to create account

### ISSUE THREAD

**Issue by rlopzc** [bdougie/casper-cms-template#5]
Hi, when I use this template I receive an email to create an account but the link doesn't work.

How do I enable the default invitation/password user creation for the CMS?

I don't want to use Github OAuth solution, just the default one

**Comment by rlopzc** [comment]
I already changed to `git-gateway` instead of `github` as provider but still cannot accept invitations
![image](https://user-images.githubusercontent.com/6199588/47259266-9cfa3580-d46c-11e8-860b-cdba507a9052.png)

Doesn't popup to set up a password

**Comment by ghost** [comment]
I'm getting this exact same thing. Have tried adjusted netlify identity settings (adding github oath, adding git gateway, changing to open rather than invite only). Nothing seems to be working. Invitation link goes to home page with access token in address like above.

**Comment by bdougie** [comment]
I recommend using https://templates.netlify.com/template/empress-blog-casper-template/ instead.
